### ISSUE TITLE
React Native Theme needs a bold font

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#94]
#### Describe the desired behavior

We need a bold font for List Item Tag 

#### Describe the current behavior

RNP does not support "bold", they only have thin, light, regular, and medium in their font styles.

#### Is this request related to a current issue?

No, but it comes from [this PR comment](https://github.com/pxblue/react-native-component-library/pull/72#discussion_r462951908)

**Comment by joebochill** [comment]
We can technically add any weights that we want to our themes. However, if our components use those weights, they will no longer be compatible with the default RNP theme, or any other custom themes that don't have the font weight. To support that, we would need to add some conditional fallback logic wherever we use the extra fonts so apps won't crash if those weights aren't available.

**Comment by joebochill** [comment]
We also need to figure out how to make the typings work. The RNP guides suggest overriding the global namespace types, but I'm not sure if we can (or should) do that in our NPM package, or if that's something that a user should do in their application.

**Comment by joebochill** [comment]
We do have a PR open on the RNP repository to add this officially to the theming system. We also have implemented the 'conditional logic' approach in the ListItemTag already to use the bold font if it exists and semibold otherwise. We can use that as a reference if we want to implement this before it becomes an official part of RNP.

**Comment by huayunh** [comment]
@joebochill update the docs for a tip to bold font users

**Comment by joebochill** [comment]
The LIT has been updated to work if a bold font exists in the theme, but the bold font has not yet actually been added to our theme (I hacked it up to make sure that it would work for the LIT in testing, but nothing has been added to the repo yet). Since the PR was rejected by RNP, we will need to go our own way for this. Doesn't make sense to update the docs until this issue is actually fixed.
